version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_hh"
      POSTGRES_PASSWORD: "test_hh"
    ports:
      - "5432:5432"
