# Generated by Django 4.1.7 on 2023-02-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_vacancy_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="address",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="employer",
            name="amount_of_employees",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="employer",
            name="contacts",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="employer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vacancy", name="salary", field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="contacts",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="worker", name="description", field=models.TextField(blank=True),
        ),
    ]
